# Generated by Django 4.1.7 on 2023-03-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_on',
            field=models.DateTimeField(),
        ),
    ]
